openapi: 3.0.3
info:
  title: OpenAPI 3.0 test validation document
  version: 0.1
paths:
  '/test':
    get:
      responses:
        '200':
          description: OK
components:
  schemas:
    TestSchema:
      type: number
      maximum: 5
      exclusiveMaximum: true
      multipleOf: a